config/routes.rb
Rails.application.routes.draw do
  get '/',
    to: 'articles#new',
    as: 'new_article'

  get '/:custom_link',
    to: 'articles#show',
    as: 'article'

  get '/:custom_link/edit',
    to: 'articles#edit',
    as: 'edit_article'

  post '/:custom_link/access_to_edit',
    to: 'articles#access_to_edit',
    as: 'access_to_edit_article'

  post '/articles',
    to: 'articles#create'

  match '/:custom_link',
    to: 'articles#update',
    via: [:patch, :put]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_secure_password(validations: false)

  validates :body,
    presence: true,
    length: { maximum: 15_000_000, message: "is too long (maximum is 15000000 characters, ~10mb)" }

  validates :body,
    format: { without: %r{\A(<p>[[:blank:]]*(<br>)?<\/p>)+\z}, message: "can't be blank" },
    on: :create

  validates :custom_link,
    length: { maximum: 100 }

  validates :password,
    length: { maximum: 100 }

  def to_param
    custom_link
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :reset_session, only: [:show, :new]

  def show
    @article = Article.find(params[:custom_link])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      new_custom_link = ClearCustomLinkService.call(article_params[:custom_link])
      redirect_to article_path(new_custom_link)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def access_to_edit
    @article = Article.find(params[:custom_link])
    if @article.authenticate(params[:password])
      session[:article_custom_link] = @article.custom_link
      redirect_to edit_article_path
    else
      flash.now[:error] = 'wrong password'
      render :show, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(session[:article_custom_link])
  end

  def update
    @article = Article.find(session[:article_custom_link])
    if @article.update(article_params)
      new_custom_link = ClearCustomLinkService.call(article_params[:custom_link])
      redirect_to article_path(new_custom_link)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:body, :custom_link, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def custom_link_without_id_for_form(custom_link)
    custom_link.blank? ? custom_link : custom_link.gsub(/\A\d+-?/, '')
  end

  def sanitized_article_body
    sanitize @article.body, tags: %w(p h1 h2 br em u s a pre img), attributes: %w(src href target)
  end
end

app/views/articles/_errors.html.erb
<% if flash[:error].present? %>
  <div class="errors"><%= flash[:error] %></div>
<% end %>

<% @article.errors.full_messages.each do |message| %>
  <div class="errors"><%= message %></div>
<% end %>

app/views/articles/_form.html.erb
<div data-controller='quill'>
  <div data-quill-target='editor'></div>

  <%= form_with model: @article, data: {action: 'quill#fill'} do |form| %>
      <%= form.hidden_field :body,
        data: {'quill-target' => 'article'}
      %>

      <%= form.password_field :password,
        placeholder: 'set password',
        class: 'password_field'
      %>

      <%= form.text_field :custom_link,
        value: custom_link_without_id_for_form(@article.custom_link),
        placeholder: 'set custom link',
        class: 'custom_link_field'
      %>

      <%= form.submit 'publish', class: 'publish_button' %>
  <% end %>
</div>

app/views/articles/_timestamps.html.erb
<% if @article.created_at.strftime("%Y-%m-%d") == @article.updated_at.strftime("%Y-%m-%d") %>
  <div class="timestamps">
    <p>created <%= @article.created_at.strftime("%Y-%m-%d") %></p>
  </div>
<% else %>
  <div class="timestamps">
    <p>created <%= @article.created_at.strftime("%Y-%m-%d") %>, last update <%= @article.updated_at.strftime("%Y-%m-%d") %></p>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render "form" %>

app/views/articles/new.html.erb
<%= render "form" %>

app/views/articles/show.html.erb
<article> <%= sanitized_article_body %> </article>

<%= render "timestamps" %>

<% if @article.password_digest.present? %>
  <%= form_with url: access_to_edit_article_path do |f| %>
    <%= f.password_field :password,
      placeholder: 'password to edit this article',
      class: "password_field" %>
    <%= f.submit "edit", class: "edit_button" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Darkw</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render "errors" %>
      <%= yield %>
    </div>
  </body>
</html>